name: Workflow Check
on:
  workflow_dispatch:
    inputs:
      GIT_COMMIT_TO_PROMOTE:
        description: 'Git commit SHA to promote'
        required: false
      ENV_TO_PROMOTE_TO:
        description: 'Environment to promote to'
        required: false
      CCB_TICKET_NUMBER:
        description: 'CCB ticket number (for a production release)'
        required: false
env:
  TEST_PLAN_KEY: "SX-1"
  PROJECT_KEY: "SX"
  TEST_EXECUTION_KEY: "SX-2"
  WORKSPACE: ${{ github.workspace }}

jobs:
  manual-deploy:
    runs-on: [self-hosted, Standard]
    name: XRay Tests and Email confirmation
    steps:
      - name: Import results to Xray
        uses: mikepenz/xray-action@4980975100b1cbc495c005ed427db98dd9d0332f
        with:
          username: ${{ secrets.SX_JIRA_USER}}
          password: ${{ secrets.SX_JIRA_PASSWORD}}
          testFormat: "junit"
          testPaths: "*.xml"
          testExecKey: ${{env.TEST_EXECUTION_KEY}}
          testPlanKey: ${{env.TEST_PLAN_KEY}}
          testMerge: false
          projectKey: ${{env.PROJECT_KEY}}
          failOnImportError: true
