name: Workflow Check
on:
  workflow_dispatch:
    inputs:
      GIT_COMMIT_TO_PROMOTE:
        description: 'Git commit SHA to promote'
        required: false
      ENV_TO_PROMOTE_TO:
        description: 'Environment to promote to'
        required: false
env:
  TEST_PLAN_KEY: "SX-1"
  PROJECT_KEY: "SX"
  TEST_EXECUTION_KEY: "SX-2"
  WORKSPACE: ${{ github.workspace }}

jobs:
  manual-deploy:
    runs-on: [self-hosted, Standard]
    name: XRay Tests
