name: Workflow Check

on: [push]
  
jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Import results to Xray
        uses: mikepenz/xray-action@07bcd51904dc36926c3659ba9021dfd51e092055
        with:
          username: ${{ secrets.SX_JIRA_USER}}
          password: ${{ secrets.SX_JIRA_PASSWORD}}
          testFormat: "junit"
          testPaths: "**/*.xml"
          testExecKey: "SX-19"
          testPlanKey: "SX-18"
          testMerge: false
          projectKey: "SX"
          failOnImportError: true
