name: Workflow Check

on: [push]
  
jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Display Day of Week
        run: echo $DAY_OF_WEEK
      - name: Import results to Xray
        uses: mikepenz/xray-action@4980975100b1cbc495c005ed427db98dd9d0332f
        with:
          username: ${{ secrets.SX_JIRA_USER}}
          password: ${{ secrets.SX_JIRA_PASSWORD}}
          testFormat: "junit"
          testPaths: "/*.xml"
          testExecKey: "SX-7"
          testPlanKey: "SX-6"
          testMerge: false
          projectKey: "SX"
          failOnImportError: true
